on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment to deploy to?'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
jobs:
  build:                       
    runs-on: ubuntu-latest      
    steps:
      - uses: actions/checkout@v4
